import { Router } from "express";
import { z } from "zod";
import { prisma } from "../db";
import { body, HttpError, ownedLesson } from "../http";
import { LESSON_TYPES, type LessonFilesDTO } from "../../shared/types";
import { LESSON_TEMPLATES } from "../../shared/templates";
import { hasMeaningfulContent } from "../../shared/planning";
import { extractActionItems } from "../services/ai/extractActions";
import { ensureLessonFolder, lessonInclude, toLessonDTO } from "../services/lessons";

export const lessonsRouter = Router();

const DAY = 86_400_000;
/** Default lead time for an extracted action item with no stated deadline. */
const ACTION_LEAD_DAYS = 2;

async function lessonDTO(id: string) {
  return toLessonDTO(await prisma.lesson.findUniqueOrThrow({ where: { id }, include: lessonInclude }));
}

/** Lessons whose slot falls on a given local date — backs the dashboard day slide-over. */
lessonsRouter.get("/", async (req, res) => {
  const { date } = z.object({ date: z.iso.date() }).parse(req.query);
  const start = new Date(`${date}T00:00:00`);
  const end = new Date(start.getTime() + DAY);
  const lessons = await prisma.lesson.findMany({
    where: { subject: { userId: req.ctx.userId }, calendarEvents: { some: { startTime: { gte: start, lt: end } } } },
    include: { ...lessonInclude, subject: true },
  });
  const out = await Promise.all(
    lessons.map(async (l) => ({
      ...toLessonDTO(l),
      subjectName: l.subject.name,
      subjectColor: l.subject.color,
      files: l.folderPath ? (await req.ctx.storage.list(l.folderPath).catch(() => [])).slice(0, 5) : [],
    })),
  );
  out.sort((a, b) => (a.slot?.startTime ?? "").localeCompare(b.slot?.startTime ?? ""));
  res.json(out);
});

lessonsRouter.get("/:id", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  res.json(await lessonDTO(lesson.id));
});

const LessonPatch = z.object({
  title: z.string().trim().max(200).optional(), // empty = label by position
  bodyText: z.string().max(200_000).optional(),
  lessonType: z.enum(LESSON_TYPES).optional(),
  homeworkText: z.string().max(20_000).nullable().optional(),
  homeworkOffset: z.number().int().min(0).max(60).nullable().optional(),
});

lessonsRouter.patch("/:id", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  const patch = body(LessonPatch, req);
  const bodyChanged = patch.bodyText !== undefined && patch.bodyText !== lesson.bodyText;
  const homeworkChanged =
    (patch.homeworkText !== undefined && patch.homeworkText !== lesson.homeworkText) ||
    (patch.homeworkOffset !== undefined && patch.homeworkOffset !== lesson.homeworkOffset);

  await prisma.lesson.update({
    where: { id: lesson.id },
    data: {
      ...patch,
      ...(patch.bodyText !== undefined && { isPlanned: hasMeaningfulContent(patch.bodyText) }),
      // Editing homework after posting puts it back in the queue.
      ...(homeworkChanged && { homeworkPostedAt: null }),
    },
  });

  let actionItems: { title: string; dueDate: string }[] | undefined;
  let warning: string | undefined;
  if (bodyChanged) {
    const r = await syncActionItems(req.ctx.userId, lesson.id, patch.bodyText!);
    actionItems = r.items;
    warning = r.warning;
  }
  res.json({ lesson: await lessonDTO(lesson.id), actionItems, warning });
});

/**
 * Scans notes for operational to-dos and mirrors them into auto-generated
 * tasks. Open auto tasks for the lesson are replaced; completed ones are kept
 * and not re-created.
 */
async function syncActionItems(userId: string, lessonId: string, bodyText: string) {
  const lesson = await prisma.lesson.findUniqueOrThrow({
    where: { id: lessonId },
    include: { subject: true, calendarEvents: { orderBy: { startTime: "asc" }, take: 1 } },
  });
  const now = new Date();
  const lessonDate = lesson.calendarEvents[0]?.startTime ?? null;
  const { items, warning } = await extractActionItems(bodyText, {
    lessonTitle: lesson.title || `Lesson ${lesson.sequenceOrder + 1}`,
    subjectName: lesson.subject.name,
    lessonDate,
    today: now,
  });

  const existing = await prisma.task.findMany({ where: { lessonId, isAutoGenerated: true } });
  const done = new Set(existing.filter((t) => t.isCompleted).map((t) => t.title.toLowerCase()));
  const fresh = items.filter((i) => !done.has(i.title.toLowerCase()));
  const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const due = (d: string | null) => {
    if (d) return new Date(`${d}T09:00:00`);
    if (!lessonDate) return new Date(startOfToday.getTime() + 7 * DAY);
    const lead = new Date(lessonDate.getTime() - ACTION_LEAD_DAYS * DAY);
    return lead < startOfToday ? startOfToday : lead;
  };

  await prisma.$transaction([
    prisma.task.deleteMany({ where: { lessonId, isAutoGenerated: true, isCompleted: false } }),
    ...fresh.map((i) =>
      prisma.task.create({ data: { userId, title: i.title, dueDate: due(i.dueDate), isAutoGenerated: true, lessonId } }),
    ),
  ]);
  return { items: fresh.map((i) => ({ title: i.title, dueDate: due(i.dueDate).toISOString() })), warning };
}

/** Template injection: prepend or replace notes, set the lesson type, create the folder when the template asks for one. */
lessonsRouter.post("/:id/template", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  const { type, mode } = body(z.object({ type: z.enum(LESSON_TYPES), mode: z.enum(["insert", "replace"]).default("insert") }), req);
  const template = LESSON_TEMPLATES[type];
  const bodyText = mode === "replace" || !lesson.bodyText.trim() ? template.body : `${template.body}\n${lesson.bodyText}`;
  await prisma.lesson.update({
    where: { id: lesson.id },
    data: { bodyText, lessonType: type, isPlanned: hasMeaningfulContent(bodyText) },
  });
  if (template.createsFolder) await ensureLessonFolder(req.ctx.userId, lesson.id, req.ctx.storage);
  res.json({ lesson: await lessonDTO(lesson.id) });
});

lessonsRouter.post("/:id/folder", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  const folderPath = await ensureLessonFolder(req.ctx.userId, lesson.id, req.ctx.storage);
  res.json({ folderPath });
});

lessonsRouter.post("/:id/folder/open", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  const folderPath = await ensureLessonFolder(req.ctx.userId, lesson.id, req.ctx.storage);
  await req.ctx.storage.reveal(folderPath);
  res.json({ folderPath });
});

lessonsRouter.get("/:id/files", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  const out: LessonFilesDTO = { folderPath: lesson.folderPath, exists: false, files: [] };
  if (lesson.folderPath) {
    out.exists = await req.ctx.storage.exists(lesson.folderPath);
    out.files = out.exists ? await req.ctx.storage.list(lesson.folderPath) : [];
  }
  res.json(out);
});

lessonsRouter.post("/:id/homework/post", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  if (!lesson.homeworkText?.trim()) throw new HttpError(400, "This lesson has no homework text");
  const slot = await prisma.calendarEvent.findFirst({ where: { lessonId: lesson.id }, orderBy: { startTime: "asc" } });
  const result = await req.ctx.lms.postHomework({
    lessonId: lesson.id,
    subjectName: lesson.subject.name,
    group: slot?.group ?? null,
    lessonDate: slot?.startTime ?? new Date(),
    title: lesson.title || `Lesson ${lesson.sequenceOrder + 1}`,
    body: lesson.homeworkText,
  });
  await prisma.lesson.update({ where: { id: lesson.id }, data: { homeworkPostedAt: result.postedAt } });
  res.json({ lesson: await lessonDTO(lesson.id), via: req.ctx.lms.displayName });
});

lessonsRouter.delete("/:id/homework/post", async (req, res) => {
  const lesson = await ownedLesson(req, req.params.id);
  await prisma.lesson.update({ where: { id: lesson.id }, data: { homeworkPostedAt: null } });
  res.json({ lesson: await lessonDTO(lesson.id) });
});
