import { Router } from "express";
import { z } from "zod";
import type { Prisma } from "@prisma/client";
import { prisma } from "../db";
import { body, HttpError } from "../http";
import type { TaskDTO } from "../../shared/types";
import { lessonLabel } from "../../shared/planning";

export const tasksRouter = Router();

const taskInclude = { lesson: { select: { title: true, sequenceOrder: true, subject: { select: { name: true, color: true } } } } } satisfies Prisma.TaskInclude;
type TaskRow = Prisma.TaskGetPayload<{ include: typeof taskInclude }>;

export function toTaskDTO(t: TaskRow): TaskDTO {
  return {
    id: t.id,
    title: t.title,
    dueDate: t.dueDate.toISOString(),
    isCompleted: t.isCompleted,
    isAutoGenerated: t.isAutoGenerated,
    lessonId: t.lessonId,
    lessonTitle: t.lesson ? lessonLabel(t.lesson) : null,
    subjectName: t.lesson?.subject.name ?? null,
    subjectColor: t.lesson?.subject.color ?? null,
  };
}

export async function listTasks(userId: string, includeCompleted: boolean): Promise<TaskDTO[]> {
  const since = new Date(Date.now() - 2 * 86_400_000);
  const tasks = await prisma.task.findMany({
    where: { userId, ...(includeCompleted ? {} : { OR: [{ isCompleted: false }, { isCompleted: true, dueDate: { gte: since } }] }) },
    include: taskInclude,
    orderBy: [{ isCompleted: "asc" }, { dueDate: "asc" }],
  });
  return tasks.map(toTaskDTO);
}

tasksRouter.get("/", async (req, res) => {
  res.json(await listTasks(req.ctx.userId, req.query.all === "1"));
});

tasksRouter.post("/", async (req, res) => {
  const t = body(z.object({ title: z.string().trim().min(1).max(300), dueDate: z.iso.date(), lessonId: z.string().nullable().optional() }), req);
  if (t.lessonId) {
    const owned = await prisma.lesson.count({ where: { id: t.lessonId, subject: { userId: req.ctx.userId } } });
    if (!owned) throw new HttpError(404, "Lesson not found");
  }
  const task = await prisma.task.create({
    data: { userId: req.ctx.userId, title: t.title, dueDate: new Date(`${t.dueDate}T09:00:00`), lessonId: t.lessonId ?? null },
    include: taskInclude,
  });
  res.status(201).json(toTaskDTO(task));
});

tasksRouter.patch("/:id", async (req, res) => {
  const p = body(z.object({ title: z.string().trim().min(1).max(300).optional(), dueDate: z.iso.date().optional(), isCompleted: z.boolean().optional() }), req);
  const existing = await prisma.task.findFirst({ where: { id: req.params.id, userId: req.ctx.userId } });
  if (!existing) throw new HttpError(404, "Task not found");
  const task = await prisma.task.update({
    where: { id: existing.id },
    data: { ...p, ...(p.dueDate && { dueDate: new Date(`${p.dueDate}T09:00:00`) }) },
    include: taskInclude,
  });
  res.json(toTaskDTO(task));
});

tasksRouter.delete("/:id", async (req, res) => {
  const { count } = await prisma.task.deleteMany({ where: { id: req.params.id, userId: req.ctx.userId } });
  if (!count) throw new HttpError(404, "Task not found");
  res.status(204).end();
});
