// Types shared by the API server and the React client.

export const EVENT_TYPES = ["lesson", "pause", "meeting", "supervision", "other"] as const;
export type EventType = (typeof EVENT_TYPES)[number];

export const LESSON_TYPES = ["standard", "lab", "test", "excursion", "project"] as const;
export type LessonType = (typeof LESSON_TYPES)[number];

export type LessonStatus = "done" | "planned" | "needs-plan" | "unplanned" | "no-slot";

/** Days ahead in which an empty lesson counts as "needs plan". */
export const UNPLANNED_ALERT_DAYS = 14;

export interface SlotDTO {
  eventId: string;
  startTime: string;
  endTime: string;
  room: string | null;
  group: string | null;
}

export interface LessonDTO {
  id: string;
  subjectId: string;
  sequenceOrder: number;
  title: string;
  lessonType: LessonType;
  bodyText: string;
  folderPath: string | null;
  homeworkText: string | null;
  homeworkOffset: number | null;
  homeworkPostedAt: string | null;
  isPlanned: boolean;
  slot: SlotDTO | null;
  status: LessonStatus;
  openTaskCount: number;
}

export interface SubjectStats {
  completed: number;
  planned: number;
  remainingSlots: number;
  totalSlots: number;
}

export interface SubjectDTO {
  id: string;
  name: string;
  color: string;
  isVisible: boolean;
  stats: SubjectStats;
}

export interface CalendarEventDTO {
  id: string;
  summary: string;
  startTime: string;
  endTime: string;
  eventType: EventType;
  subjectName: string | null;
  subjectId: string | null;
  subjectColor: string | null;
  group: string | null;
  room: string | null;
  isPause: boolean;
  isIgnored: boolean;
  lessonId: string | null;
}

export interface TaskDTO {
  id: string;
  title: string;
  dueDate: string;
  isCompleted: boolean;
  isAutoGenerated: boolean;
  lessonId: string | null;
  lessonTitle: string | null;
  subjectName: string | null;
  subjectColor: string | null;
}

export interface HomeworkQueueItem {
  lessonId: string;
  lessonTitle: string;
  subjectName: string;
  subjectColor: string;
  homeworkText: string;
  releaseDate: string;
  lessonDate: string;
  postedAt: string | null;
}

export interface DashboardDTO {
  subjects: SubjectDTO[];
  unplanned: (LessonDTO & { subjectName: string; subjectColor: string })[];
  homework: HomeworkQueueItem[];
  tasks: TaskDTO[];
}

export interface SettingsDTO {
  icalUrl: string | null;
  teachingRoot: string;
  schoolYearStart: string | null;
  schoolYearEnd: string | null;
  hiddenEventTypes: EventType[];
  lastSyncAt: string | null;
  lastSyncSummary: string | null;
  aiEnabled: boolean;
  aiModel: string;
  platform: NodeJS.Platform | string;
}

export interface SyncResult {
  fetched: number;
  created: number;
  updated: number;
  removed: number;
  subjectsCreated: number;
  lessonsCreated: number;
  aiParsed: number;
  heuristicParsed: number;
  warnings: string[];
}

export interface FileEntry {
  name: string;
  isDirectory: boolean;
  size: number;
  modifiedAt: string;
}

export interface LessonFilesDTO {
  folderPath: string | null;
  exists: boolean;
  files: FileEntry[];
}
